version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/Test1Project
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.test1.integrations:e1
  packages:
  - name: Test1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.991
